### ISSUE TITLE
Add support for HTTPS

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DNP_ETHFORWARD#10]
Since the ledger doesn't work without HTTPS connections, we must look for ways to support this type of connections

**Comment by Shelpin** [comment]
Could we get this out of the icebox??either internally or with a bounty

**Comment by dapplion** [comment]
Closing since this is an extremely sensitive and potentially centralizing topic. The DAppNode team has debated how to achieve this for over a year and will implement when a solution that respects our core values of decentralization is found.
