### ISSUE TITLE
Aragon Decentralized WebUI not loading apps / Update to Aragon 0.6  Alba

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_ETHFORWARD#11]
When you try to  join an org through http://aragon.dappnode.eth/#, the  screen gets stuck in loading apps...I have tried several times and  a couple of them it loaded (voting, Finance and token manager) but  after loading  they do not  perform any action. Not sure if it is an Aragon issue or it is about the site, just for you to know. Quite sure  that it very likely does not correspond to ETHFORWARD, but i found it the best fit . 

![image](https://user-images.githubusercontent.com/21328788/46691668-bb0e9d00-cc05-11e8-803b-d6adb39a7ba1.png)

**Comment by dapplion** [comment]
@Shelpin It has also happened to me. Please, could you try back to back the DAppNode's version of the aragon app, and the actual aragon app? Maybe it's a bug of our implementation.

**Comment by Shelpin** [comment]
That only happened to me in our implementation of Aragon 0.5, still as they have moved to 0.6 we will have to redo our implementation or talk with Aragon to implement it in their access to Aragon

**Comment by Shelpin** [comment]
Maybe we  could redirect this issue (close it) and make the issue about updating our current implementation to Aragon 0.6

**Comment by Shelpin** [comment]
just changed the topic for including the update to 0.6 and not closing and opening a new  one

**Comment by vporton** [comment]
It also happens in 0.8 Camino after I cleared the cache in Aragon settings :-(

**Comment by vporton** [comment]
^^^ On Chrome, at least.

**Comment by vporton** [comment]
On Firefox the same bug. And I noticed the error message:

> The connection to wss://mainnet.eth.aragon.network/ws was interrupted while the page was loading.

**Comment by dapplion** [comment]
@eduadiez
